'use client'

import { BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer, Cell, LabelList } from 'recharts'
import SpendBreakdown from '@/components/SpendBreakdown'

type CategoryData = {
  category: string
  amount: number
}

const COLORS = {
  Income: 'var(--color-sg-400)',
  Expenses: 'var(--color-danger-400)',
}

function formatDollar(value: number) {
  return `$${Math.round(value).toLocaleString('en-US')}`
}

function CustomTooltip({ active, payload }: { active?: boolean; payload?: Array<{ payload: { name: string; value: number } }> }) {
  if (!active || !payload?.length) return null
  const { name, value } = payload[0].payload
  return (
    <div className="card" style={{ padding: '8px 12px', minWidth: 0 }}>
      <div className="text-label font-medium text-neutral-700">{name}</div>
      <div className="text-[18px] font-semibold text-neutral-900 tabular-nums">{formatDollar(value)}</div>
    </div>
  )
}

export default function Dashboard({ income, expenses, monthLabel, categoryBreakdown, insight }: { income: number; expenses: number; monthLabel: string; categoryBreakdown: CategoryData[]; insight?: string }) {
  const chartData = [
    { name: 'Income', value: income },
    { name: 'Expenses', value: expenses },
  ]

  return (
    <div className="px-6 lg:px-10 py-8">
      <h1 className="text-hero font-display text-neutral-900 mb-6">Hello, Devin!</h1>

      {/* AI Insight card */}
      {insight && (
        <div className="card-tinted mb-8">
          <div className="flex items-start gap-3">
            <svg className="w-5 h-5 text-sg-500 mt-0.5 shrink-0" viewBox="0 0 20 20" fill="currentColor">
              <path d="M10 1l2.39 6.17L19 8.24l-5 4.36L15.18 19 10 15.77 4.82 19 6 12.6 1 8.24l6.61-1.07L10 1z" />
            </svg>
            <div className="flex-1">
              <p className="text-body text-neutral-600 italic font-display">{insight}</p>
              <p className="text-[13px] text-neutral-400 mt-3 text-right">Generated by Claude</p>
            </div>
          </div>
        </div>
      )}

      {/* Income vs Expenses card */}
      <div className="card mb-8">
        {monthLabel && <div className="stat-label mb-4 text-neutral-800">{monthLabel}</div>}

        <ResponsiveContainer width="100%" height={160}>
          <BarChart data={chartData} barGap={12} margin={{ top: 24, right: 0, bottom: 0, left: 0 }}>
            <XAxis dataKey="name" axisLine={false} tickLine={false} tick={{ fontSize: 15, fill: 'var(--color-neutral-500)' }} />
            <YAxis hide />
            <Tooltip content={<CustomTooltip />} cursor={false} />
            <Bar dataKey="value" radius={[6, 6, 0, 0]} maxBarSize={64}>
              {chartData.map((entry) => (
                <Cell key={entry.name} fill={COLORS[entry.name as keyof typeof COLORS]} />
              ))}
              <LabelList
                dataKey="value"
                position="top"
                formatter={((value: unknown) => formatDollar(Number(value ?? 0))) as never}
                style={{ fontSize: 14, fontWeight: 600, fill: 'var(--color-neutral-700)' }}
              />
            </Bar>
          </BarChart>
        </ResponsiveContainer>

        <div className="flex justify-between mt-4 pt-4 border-t border-neutral-100">
          <div>
            <span className="text-label font-medium text-neutral-600">Income</span>
            <div className="stat-value text-sg-400 text-[24px]">
              ${income.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
            </div>
          </div>
          <div className="text-right">
            <span className="text-label font-medium text-neutral-600">Expenses</span>
            <div className="stat-value text-danger-400 text-[24px]">
              ${expenses.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
            </div>
          </div>
        </div>
      </div>

      {/* Spend Breakdown */}
      <SpendBreakdown data={categoryBreakdown} monthLabel={monthLabel} />
    </div>
  )
}
